config/routes.rb
Rails.application.routes.draw do
  root to: 'maps#index'

  devise_for :admins, skip: :all
  devise_scope :admin do
    get 'admin/sign_in' , to: 'admins/sessions#new', as: :new_admin_session
    post 'admin/sign_in' , to: 'admins/sessions#create', as: :admin_session
    delete 'admin/sign_out' , to: 'admins/sessions#destroy', as: :destroy_admin_session
  end

  resources :maps, :except => [:destroy, :update, :show, :edit] do
    get 'about', :on => :collection
    get 'download', :on => :collection
  end

  resources :aed_information_managements , :except => [:new, :show] do
    get 'csv_import', :on => :collection
    get 'search', :on => :collection
  end

end

app/controllers/aed_information_managements_controller.rb
class AedInformationManagementsController < ApplicationController
  def index
      @aed_inf = AedInformation.where(registration_status: false)
  end

  def create
    CSV.read(params[:file_select].path, headers: true).each do |row|

      if row['設置位置'].nil?
        row['設置位置'] = ""
      end

      AedInformation.create(
              latitude: row['緯度'],
              longitude: row['経度'],
              facility: row['施設名'],
              installation_location: row['設置位置'],
              aed_image_id: "",
              registration_status: true,
              prefecture: row['都道府県'],
              address: row['住所'],
              phone_number: row['電話番号']
          )

      # if AedInformation.where(facility: row['施設名']).where(installation_location: row['設置位置']).blank?
      #   unless row['緯度'].nil? || row['経度'].nil?
      #     if row['施設名'].nil?
      #       row['施設名'] = ""
      #     end
      #     if row['設置位置'].nil?
      #       row['設置位置'] = ""
      #     end
      #
      #     if row['都道府県'].nil?
      #       row['都道府県'] = ""
      #     end
      #     if row['住所'].nil?
      #       row['住所'] = ""
      #     end
      #     if row['電話番号'].nil?
      #       row['電話番号'] = ""
      #     end
      #     AedInformation.create(
      #         latitude: row['緯度'],
      #         longitude: row['経度'],
      #         facility: row['施設名'],
      #         installation_location: row['設置位置'],
      #         aed_image_id: "",
      #         registration_status: true,
      #         prefecture: row['都道府県'],
      #         address: row['住所'],
      #         phone_number: row['電話番号']
      #     )
      #   end
      # end
    end

    redirect_to aed_information_managements_path
  end

  def edit
    if request.xhr?
      if params['mode'] == "position"
        query = params['search_word']
        base_url = 'https://map.yahooapis.jp/search/local/V1/localSearch'
        request = {
            'appid' => ENV['YAHOO_CLIENT_ID'],
            'query' => query,
            'results' => 100,
            'detail' => 'full',
            'output' => 'json'
        }
        url = base_url + '?' + URI.encode_www_form(request)
        json = open(url).read
        data = JSON.parse(json)
        @response = []
        data['Feature'].each do |feature|
          latitude = feature['Geometry']['Coordinates'].split(",")[1].to_f
          longitude = feature['Geometry']['Coordinates'].split(",")[0].to_f
          @response.push({name: feature['Name'] , geometry: [latitude, longitude]})
        end

      elsif params['mode'] == 'address'

        #緯度経度から住所取得
        base_url = 'https://map.yahooapis.jp/geoapi/V1/reverseGeoCoder'
        request = {
            'appid' => ENV['YAHOO_CLIENT_ID'],
            'lat' => params['search_latlon'][0],
            'lon' => params['search_latlon'][1],
            'output' => 'json'
        }
        url = base_url + '?' + URI.encode_www_form(request)
        json = open(url).read
        data = JSON.parse(json)

        prefecture = data['Feature'][0]['Property']['AddressElement'][0]['Name']
        address = data['Feature'][0]['Property']['Address'].split(prefecture)[1]
        # @response = {prefecture: prefecture, address: address}

        #住所から郵便番号取得
        base_url = 'https://zipcoda.net/api'
        request = {
            'address' => data['Feature'][0]['Property']['Address']
        }
        url = base_url + '?' + URI.encode_www_form(request)
        json = open(url).read
        data = JSON.parse(json)

        @response = {prefecture: prefecture, address: address, zipcode: data['items'][0]['zipcode']}

      elsif params['mode'] == 'latlon'
        base_url = 'https://map.yahooapis.jp/geocode/V1/geoCoder'
        request = {
            'appid' => ENV['YAHOO_CLIENT_ID'],
            'query' => params['search_address'],
            'output' => 'json'
        }
        url = base_url + '?' + URI.encode_www_form(request)
        json = open(url).read
        data = JSON.parse(json)
        lonlat = data['Feature'][0]['Geometry']['Coordinates'].split(',')
        @response = {lon: lonlat[0], lat: lonlat[1]}

      end

    else
      @aed_inf = AedInformation.find(params["id"].to_i)
      gon.aed_inf = @aed_inf

      if @aed_inf['business_day'].nil?
        @business = %w("0" "0" "0" "0" "0" "0" "0" "0")
      else
        @business = @aed_inf['business_day'].chars
      end
    end
  end

  def update
    business = ""
    if aed_update_params.has_key?('business_day')
      is_zero = true
      8.times do |i|
        aed_update_params['business_day'].each do |check_num|
          if i.to_s == check_num
            business = business + "1"
            is_zero = false
            break
          end
        end
        if is_zero
          business = business + "0"
        else
          is_zero = true
        end
      end
    else
      business = "00000000"
    end


    update_prams = aed_update_params
    update_prams['registration_status'] = true
    update_prams['business_day'] = business

    AedInformation.find(params['id']).update(update_prams)
    redirect_to aed_information_managements_path
  end

  def destroy
    AedInformation.find(params['id']).destroy
    redirect_to aed_information_managements_path
  end

  def csv_import
  end

  def search
    @select_mode = params['format']
    if params['format'] == '承認済'
      @aed_inf = AedInformation.where(registration_status: true).where(prefecture: '北海道')
    elsif params['format'] == '未承認'
      @aed_inf = AedInformation.where(registration_status: false)
    else
      @select_mode = '承認済'
        @aed_inf = AedInformation.where(prefecture: params['search_prefecture'])
    end
  end

  private
  def aed_update_params
    params.require(:aed_information).permit(:latitude, :longitude, :facility,
                                            :installation_location, :postal_code,
                                            :prefecture, :address, :phone_number,
                                            :installation_date, :start_time, :end_time, :expiration_date, business_day: [])
  end
 
end

app/helpers/aed_information_managements_helper.rb
module AedInformationManagementsHelper
end

app/views/aed_information_managements/_main_content.html.erb
  <% aed_inf_array.each_with_index do |aed_inf, index| %>
    <% if (index+1)%3 == 0 %>
      <div class="list-row"><div><%= aed_inf['created_at'].strftime('%Y/%m/%d') %>　<%= aed_inf['facility'] %></div> <%= link_to "編集", edit_aed_information_management_path(aed_inf['id']),class: "edit-aed-inf btn btn-primary" %></div><br>
    <% else %>
      <div class="list-row"><div><%= aed_inf['created_at'].strftime('%Y/%m/%d') %>　<%= aed_inf['facility'] %></div> <%= link_to "編集", edit_aed_information_management_path(aed_inf['id']),class: "edit-aed-inf btn btn-primary" %></div>
    <% end %>
  <% end %>

app/views/aed_information_managements/csv_import.html.erb
<%= render 'header/admin_header' %>

<div class="import_form">
  <%= form_with url: aed_information_managements_path, local: true, method: :post do |form| %>
    <div class="form-group form-group-sm">
      <label class="file_select_label">CSVファイル選択</label>
      <div>
        <%= form.file_field :file_select, class: "form-control", style: "display:none" %>

        <div class="input-group file-select">
          <span class="input-group-btn">
            <button type="button" id="file_select_icon" class="btn btn-sm"><span class="glyphicon glyphicon-folder-open" aria-hidden="true" style="font-size: 30px"></span></button>
          </span>
          <input type="text" id="file_name" class="form-control" placeholder="Select file ..." readonly>
        </div>
      </div>
    </div>

    <div class="form-group form-group-sm">
      <div>
        <%= form.submit 'インポート', class: "import_submit btn-lg btn-sm btn-primary" %>
        <button type="button" class="btn-lg btn-sm btn-warning" id="btn_clear_file">クリア</button>
      </div>
    </div>
  <% end %>
</div>

app/views/aed_information_managements/edit.html.erb
<%= render 'header/admin_header' %>

<% date_array = %w(月 火 水 木 金 土 日 祝日) %>
<div class="edit_form">
  <div class="aed_inf_view">
    <div id="editMap"></div>
    <div class="aed_inf_view_image">
      <%if @aed_inf['aed_image_id'] == "" %>
        <%= image_tag '/noimage.png', style: 'width:600; height:480px;' %>
      <% else %>
        <%= attachment_image_tag @aed_inf, :aed_image, :fill, 800, 680, format: 'jpeg' %>
      <% end %>
    </div>
  </div>

  <div class="aed_edit_form">
    <%= form_with model: @aed_inf,url: aed_information_management_path, method: :patch,local: true do |form| %>

      <h3>位置情報</h3>
      <div class="edit_form_position">
        <p class="edit_latlng">緯度 <%= form.text_field :latitude %> 経度 <%= form.text_field :longitude %>  <input type="button" class="search_latlon_submit btn btn-primary" value="住所から検索"></p>
        <p>施設名 <%= form.text_field :facility %> 設置場所 <%= form.text_field :installation_location %></p>
        <p>郵便番号 <%= form.text_field :postal_code %> 都道府県 <%= form.text_field :prefecture %> 住所 <%= form.text_field :address %> <input type="button" class="search_address_submit btn btn-primary" value="緯度経度から検索"></p>
      </div>

      <h3>施設情報</h3>
      <div class="edit_form_facility_detail">
        <p>設置日 <%= form.date_field :installation_date %> 有効期限 <%= form.date_field :expiration_date %></p>
        <p>営業開始時間 <%= form.time_field :start_time %> 営業終了時間 <%= form.time_field :end_time %></p>
        <p>電話番号 <%= form.text_field :phone_number %></p>
        <p>
          営業日
          <% @business.each_with_index do |check, i| %>
            <% if check == "1" %>
              <%= form.check_box :business_day, {multiple: true, :checked => true}, i, nil %>
            <% else %>
              <%= form.check_box :business_day, {multiple: true}, i, nil %>
            <% end %>
            <%= label_tag :business_day, date_array[i] %>
          <% end %>
        </p>
      </div>

      <div class="edit-submit-btns">
        <%= form.submit '更新',class: 'edit-submit-btn btn btn-primary' %>
        <%= link_to '削除',aed_information_management_path , class: 'edit-delete-btn btn btn-danger',method: :delete %>
      </div>

    <% end %>
  </div>
</div>


<div class="search_position_form">
  <input type="text" class="search_position">
  <input type="button" class="search_position_submit btn btn-primary" value="施設名から検索">
</div>

<input type="button" class="search_modification_latlon_submit btn btn-danger" value="修正マーカーの位置を適用">

app/views/aed_information_managements/index.html.erb
<%= render 'header/admin_header' %>

<div class="state_select_btn">
  <%= link_to '未承認', search_aed_information_managements_path('未承認'), method: :get, remote: true, class: 'load-event btn btn-danger'%>
  <%= link_to '承認済', search_aed_information_managements_path('承認済'), method: :get, remote: true, class: 'load-event btn btn-light btn_border'%>
</div>

<div class="prefecture-select" style="display: none">
  <select class="prefecture-select-form">
    <% prefecture_array = ["北海道","青森県","岩手県","宮城県","秋田県","山形県","福島県",
                           "茨城県","栃木県","群馬県","埼玉県","千葉県","東京都","神奈川県",
                           "新潟県","富山県","石川県","福井県","山梨県","長野県","岐阜県",
                           "静岡県","愛知県","三重県","滋賀県","京都府","大阪府","兵庫県",
                           "奈良県","和歌山県","鳥取県","島根県","岡山県","広島県","山口県",
                           "徳島県","香川県","愛媛県","高知県","福岡県","佐賀県","長崎県",
                           "熊本県","大分県","宮崎県","鹿児島県","沖縄県"]
    %>

    <% prefecture_array.each do |prefecture| %>
      <option value = <%= prefecture %>><%= prefecture %></option>
    <% end %>
  </select>
</div>

<div class="admin_top_main">
  <%= render 'main_content', aed_inf_array: @aed_inf %>
</div>

app/views/aed_information_managements/search.js.erb
$(".admin_top_main").html('<%= escape_javascript(render("main_content", aed_inf_array: @aed_inf)) %>')
$(".state_select_btn > a").removeClass()

<% if @select_mode == '未承認' %>
  $(".state_select_btn > a:nth-child(1)").addClass('btn btn-danger')
  $(".state_select_btn > a:last-child").addClass('btn btn-light btn_border')
  $('.prefecture-select').css("display","none")
<% elsif @select_mode == '承認済' %>
  $(".state_select_btn > a:nth-child(1)").addClass('btn btn-light btn_border')
  $(".state_select_btn > a:last-child").addClass('btn btn-danger')
  $('.prefecture-select').css("display","block")
<% end %>

$("#loading").remove()