config/routes.rb
Rails.application.routes.draw do
  root to: 'maps#index'

  devise_for :admins, skip: :all
  devise_scope :admin do
    get 'admin/sign_in' , to: 'admins/sessions#new', as: :new_admin_session
    post 'admin/sign_in' , to: 'admins/sessions#create', as: :admin_session
    delete 'admin/sign_out' , to: 'admins/sessions#destroy', as: :destroy_admin_session
  end

  resources :maps, :except => [:destroy, :update, :show, :edit] do
    get 'about', :on => :collection
    get 'download', :on => :collection
  end

  resources :aed_information_managements , :except => [:new, :show] do
    get 'csv_import', :on => :collection
    get 'search', :on => :collection
  end

end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def index
    if request.xhr?

      if params['mode'] == "detail"

        @aed_inf = AedInformation.find(params['className'].split('marker')[1].to_i)

        if @aed_inf['aed_image_id'] == '' || !@aed_inf['registration_status']
          @image = helpers.asset_url("noimage.png")
        else
          @image = Refile.attachment_url(@aed_inf, :aed_image, :fill, 268, 201, format: "jpeg")
        end

        @created_at = @aed_inf['created_at'].strftime('%Y/%m/%d')

        #認証前のデータを改変
        unless @aed_inf['registration_status']
          @aed_inf["facility"] = '未承認'
          @aed_inf["installation_location"] = '未承認'
          @aed_inf["address"] = '未承認'
          @aed_inf["phone_number"] = '未承認'
        end

        if @aed_inf['phone_number'].nil?
          @aed_inf['phone_number'] = '未登録'
        end
        if @aed_inf['address'].nil?
          @aed_inf['address'] = '未登録'
        end

      elsif params['mode'] == 'find'
        @response = AedInformation.where(:prefecture => params['search_word'])

      elsif params['mode'] == 'init'
        #緯度経度から住所取得
        base_url = 'https://map.yahooapis.jp/geoapi/V1/reverseGeoCoder'
        request = {
            'appid' => ENV['YAHOO_CLIENT_ID'],
            'lat' => params['lat'],
            'lon' => params['lng'],
            'output' => 'json'
        }
        url = base_url + '?' + URI.encode_www_form(request)
        json = open(url).read
        data = JSON.parse(json)

        prefecture = data['Feature'][0]['Property']['AddressElement'][0]['Name']
        coordinateArray = AedInformation.where(:prefecture => prefecture)
        @response = {prefecture: prefecture, coordinateArray: coordinateArray}
      end

    else
      #サイト読み込み時
    end
  end

  def new
    @aed_inf = AedInformation.new
  end

  def create
    #緯度経度から住所取得
    base_url = 'https://map.yahooapis.jp/geoapi/V1/reverseGeoCoder'
    request = {
        'appid' => ENV['YAHOO_CLIENT_ID'],
        'lat' => aed_params[:latitude],
        'lon' => aed_params[:longitude],
        'output' => 'json'
    }
    url = base_url + '?' + URI.encode_www_form(request)
    json = open(url).read
    data = JSON.parse(json)

    prefecture = data['Feature'][0]['Property']['AddressElement'][0]['Name']

    create_params = aed_params
    create_params[:aed_image] = StringIO.new(Base64.decode64(aed_params[:image_url]))
    create_params.delete(:image_url)
    create_params['prefecture'] = prefecture
    AedInformation.new(create_params).save

    redirect_to maps_path

  end

  def about
    @aed_inf = AedInformation.all
  end

  def download
    respond_to do |format|
      format.html do

      end
      format.csv do
        send_data render_to_string, filename: "投稿情報.csv"
      end
    end
  end

  private
  def aed_params
    params.require(:aed_information).permit(:latitude, :aed_image, :longitude, :facility, :installation_location, :image_url)
  end

end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/maps/about.html.erb
<div class="header">
  <div class="menu-trigger-form" href=""><span></span><span></span><span></span></div>
  <div class="menu-trigger-back-form"></div>
  <nav>
    <ul class="menu-btns">
      <li><%= link_to 'AEDMAP', maps_path,class: 'btn btn-success' %></li>
      <li><%= link_to 'サイトについて', about_maps_path, class: 'btn btn-success'%></li>
      <li><%= link_to '投稿', new_map_path, class: 'btn btn-success' %></li>
      <li><%= link_to 'ダウンロード', download_maps_path, class: 'btn btn-success' %></li>
    </ul>
  </nav>
  <div class="overlay"></div>
</div>

<div class="about_main_content">
  <h2>AEDMAPの注意事項</h2>
  <p>投稿型のAEDの位置マッピングサイトになっています</p>
  <p>投稿の際やマップ表示には位置情報を使用しています</p>
  <p>閲覧ご協力いただく際は位置情報の許可をお願いします</p>
  <p>また投稿の際は位置情報の他に端末のカメラ機能を使用します</p>

  <h2>AEDMAPとは？</h2>
  <p>青色のエリアはAEDの位置を中心に半径300メートルの範囲を示しています</p>
  <p>救急車到着までに往復しても適用できる限界の距離として参考表示しています</p>
  <p>青色のマーカーは管理者が承認したAEDの情報になります</p>
  <p>赤色のマーカーは管理者がまだ承認していないAEDの情報になります</p>
  <p>マーカーを選択していただくとAEDの詳細情報が表示されます</p>

  <h2>投稿について</h2>
  <p>気軽に投稿してもらうために必要事項は以下の4点に絞っています</p>
  <p>カメラ機能を許可してAEDが設置されている場所を撮影してください</p>
  <p>場所の特定のため位置情報を許可してください</p>
  <p>施設の名前がわかればできる限り詳しくお願いします</p>
  <p>設置されている場所の詳細をお願いします</p>

  <h2>ダウンロードについて</h2>
  <p>集まった情報は承認された写真データを除く全ての情報を公開しております</p>
  <p>興味のある方はダウンロードしてご利用ください</p>
  <p>投稿型のサイトのため空のデータが複数ある場合がございます</p>
</div>

app/views/maps/download.html.erb
<div class="header">
  <div class="menu-trigger-form" href=""><span></span><span></span><span></span></div>
  <div class="menu-trigger-back-form"></div>
  <nav>
    <ul class="menu-btns">
      <li><%= link_to 'AEDMAP', maps_path,class: 'btn btn-success' %></li>
      <li><%= link_to 'サイトについて', about_maps_path, class: 'btn btn-success'%></li>
      <li><%= link_to '投稿', new_map_path, class: 'btn btn-success' %></li>
      <li><%= link_to 'ダウンロード', download_maps_path, class: 'btn btn-success' %></li>
    </ul>
  </nav>
  <div class="overlay"></div>
</div>

<div class="download_main_content">
  <h2>AED情報のダウンロード</h2>
  <p>管理者に承認されたAEDの情報を以下のボタンからCSVでダウンロードできます</p>
  <div class="download-btn">
    <%= link_to 'ダウンロード', 'download.csv', class: 'btn-lg btn-primary download-btn' %>
  </div>
</div>

app/views/maps/index.html.erb
<div class="main-map-header">
  <%= link_to 'AEDMAP', maps_path,class: 'btn btn-success' %>
  <%= link_to 'サイトについて', about_maps_path, class: 'btn btn-success'%>
  <%= link_to '投稿', new_map_path, class: 'btn btn-success' %>
  <%= link_to 'ダウンロード', download_maps_path, class: 'btn btn-success' %>
</div>

<div class="main-content">
  <div id="map">
    <% prefecture_array = ["北海道","青森県","岩手県","宮城県","秋田県","山形県","福島県",
                           "茨城県","栃木県","群馬県","埼玉県","千葉県","東京都","神奈川県",
                           "新潟県","富山県","石川県","福井県","山梨県","長野県","岐阜県",
                           "静岡県","愛知県","三重県","滋賀県","京都府","大阪府","兵庫県",
                           "奈良県","和歌山県","鳥取県","島根県","岡山県","広島県","山口県",
                           "徳島県","香川県","愛媛県","高知県","福岡県","佐賀県","長崎県",
                           "熊本県","大分県","宮崎県","鹿児島県","沖縄県"]
    %>
    <select class="map_pulldown">
      <% prefecture_array.each do |prefecture| %>
        <option value=<%= prefecture %>><%= prefecture %></option>
      <% end %>
    </select>
  </div>
  <div class="menu-trigger" href=""><span></span><span></span><span></span></div>
  <div class="menu-trigger-back"></div>
  <div class="map-header">
    <nav>
      <ul class="menu-btns">
        <li><%= link_to 'AEDMAP', maps_path,class: 'btn btn-success' %></li>
        <li><%= link_to 'サイトについて', about_maps_path, class: 'btn btn-success'%></li>
        <li><%= link_to '投稿', new_map_path, class: 'btn btn-success' %></li>
        <li><%= link_to 'ダウンロード', download_maps_path, class: 'btn btn-success' %></li>
      </ul>
    </nav>
  </div>
  <div class="overlay"></div>

</div>

app/views/maps/new.html.erb
<div class="header">
  <div class="menu-trigger-form" href=""><span></span><span></span><span></span></div>
  <div class="menu-trigger-back-form"></div>
  <nav>
    <ul class="menu-btns">
      <li><%= link_to 'AEDMAP', maps_path,class: 'btn btn-success' %></li>
      <li><%= link_to 'サイトについて', about_maps_path, class: 'btn btn-success'%></li>
      <li><%= link_to '投稿', new_map_path, class: 'btn btn-success' %></li>
      <li><%= link_to 'ダウンロード', download_maps_path, class: 'btn btn-success' %></li>
    </ul>
  </nav>
  <div class="overlay"></div>
</div>

<div class="form-main-content">
  <%= form_with model: @aed_inf, url: maps_path, method: :post, local: true, id: "aed_inf_form" do |form| %>
    <div class="image_field">
      <canvas id="canvas" style="display: none;"></canvas>
      <video id="video" autoplay="1"></video>
      <img id="image">
    </div>

    <div class="input_field form-group form-group-lg">
      <div class="name_facility_field">
        <%= form.label :facility, "施設名" %><br>
        <%= form.text_field :facility, class: "form-control" %>
      </div>

      <div class="set_position_field form-group form-group-lg">
        <%= form.label :installation_location, "設置場所" %><br>
        <%= form.text_field :installation_location, class: "form-control" %>
      </div>
    </div>

    <%= form.attachment_field :aed_image, style: 'display: none'%>
    <%= form.hidden_field :image_url %>
    <%= form.hidden_field :latitude %>
    <%= form.hidden_field :longitude %>
  <% end %>

  <div class="image_shutter_btn">
    <button id="shutter">
      <i class="fa fa-camera fa-5x"></i>
    </button>
  </div>

  <button id="retry" style="display: none" class="btn btn-danger">取り直し</button>

  <div id="aed_inf_confirm_btn">
    <button id="aed_inf_confirm" style="display: none" class="btn btn-primary">送信</button>
  </div>
</div>